name: Test

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:            
          - name: Windows 64
            os: windows-latest
            cpu: x86_64
            
          - name: Windows 32  
            os: windows-latest
            cpu: i386

          - name: Linux 64
            os: ubuntu-latest
            cpu: x86_64
          
          - name: AArch64  
            os: ubuntu-latest
            cpu: aarch64
            args: --cpu=aarch64
            
          - name: MacOS 64
            os: macos-latest
            cpu: x86_64
            args: --widgetset=cocoa
            
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Install Lazarus
        uses: ./
        with:
          cpu: ${{ matrix.config.cpu }}
          laz-branch: lazarus_2_2_0_RC1
          fpc-branch: release_3_2_2_rc1
      
      - name: Build Test
        run: |
          lazbuild ${{ matrix.config.args }} test_lazarus.lpi
          
      - name: Run Test
        if: matrix.config.name != 'AArch64'
        run: |
          ./test
